# This file is the entry point to configure your own services.
# Files in the packages/ subdirectory configure your dependencies.

# Put parameters here that don't need to change on each machine where the app is deployed
# https://symfony.com/doc/current/best_practices.html#use-parameters-for-application-configuration
parameters:

services:
    # default configuration for services in *this* file
    _defaults:
        autowire: true      # Automatically injects dependencies in your services.
        autoconfigure: true # Automatically registers your services as commands, event subscribers, etc.

    # makes classes in src/ available to be used as services
    # this creates a service per class whose id is the fully-qualified class name
    App\:
        resource: '../src/'
        exclude:
            - '../src/DependencyInjection/'
            - '../src/Entity/'
            - '../src/Kernel.php'
    App\Service\OtpStorage\OtpStorageInterface:
        class: App\Service\OtpStorage\OtpStorageRedis
        arguments:
            - 'localhost'
            - '%env(string:REDIS_PORT)%'
            - '%env(string:REDIS_USER)%'
            - '%env(string:REDIS_USER_PASSWORD)%'
            - 15
    App\Service\OtpGenerator:
        arguments:
            - !php/enum App\Service\OtpCharset::NUMBER
            - 6

    # add more service definitions when explicit configuration is needed
    # please note that last definitions always *replace* previous ones
